import type { Metadata } from "next";
import { Inter_Tight, Geist } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { currentUser } from "@clerk/nextjs/server";
import { QueryProvider } from "@/providers/QueryProvider";
import { UserProvider } from "@/providers/UserProvider";
import { ThemeProvider } from "@/providers/ThemeProvider";
import { TooltipProvider } from "@/components/ui/tooltip";
import { cn } from "@/lib/utils";

const interTight = Inter_Tight({
  variable: "--font-inter-tight",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "project - notes",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: any) {
  const user = await currentUser();
  const initialUser = user
    ? {
        id: user.id,
        imageUrl: user.imageUrl,
        firstName: user.firstName,
        lastName: user.lastName,
        fullName: user.fullName,
        primaryEmailAddress: user.emailAddresses?.[0]?.emailAddress,
      }
    : null;

  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={cn("h-full", "antialiased", interTight.variable, "font-sans")}
    >
      <body className="min-h-full flex flex-col">
        <ClerkProvider>
          <QueryProvider>
            <UserProvider initialUser={initialUser}>
              <ThemeProvider
                attribute="class"
                defaultTheme="system"
                enableSystem
                disableTransitionOnChange
              >
                <TooltipProvider>
                  {children}
                </TooltipProvider>
              </ThemeProvider>
            </UserProvider>
          </QueryProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
